export const treeData = {
  fieldItems: [
    {
      type: 'chain-select',
      settings: {
        dataIndex: 'aggregateTypes',
        title: '汇总方式',
        search: 'only',
        showSearch: true,
        valueEnums: {
          SALE: '销售',
          CLIENT_TYPE: '交易对手类型',
          BUSINESS_TYPE: '业务类型',
          ENTITY_TYPE: '机构/产品类型',
          COUNTER_PARTY: '交易对手',
        },
        initialValue: ['SALE', 'CLIENT_TYPE'],
      },
    },
    {
      type: 'text',
      settings: {
        title: '客户数',
        dataIndex: 'customerNumber',
      },
    },
    {
      type: 'text',
      settings: {
        title: '初始名义本金（存续交易）',
        dataIndex: 'subsistingInitialNotionalAmount',
      },
    },
    {
      type: 'text',
      settings: {
        title: '初始名义本金（非存续交易）',
        dataIndex: 'noSubsistingInitialNotionalAmount',
      },
    },
    {
      type: 'text',
      settings: {
        title: '初始名义本金总金额',
        dataIndex: 'initialNotionalAmountTotal',
      },
    },
  ],
  totalCount: 6,
  page: [
    {
      id: 'SALE|销售1',
      aggregateKey: '销售1',
      aggregateType: 'SALE',
      aggregateTypeZH: '销售',
      customerNumber: 9,
      subsistingInitialNotionalAmount: 6251953.85319218006,
      noSubsistingInitialNotionalAmount: 5328872.637847458142,
      initialNotionalAmountTotal: 11580826.491039638202,
      children: [
        {
          id: 'CLIENT_TYPE|产品户',
          aggregateKey: '产品户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 5,
          subsistingInitialNotionalAmount: 2031968.28405107096,
          noSubsistingInitialNotionalAmount: 3878397.916216365575,
          initialNotionalAmountTotal: 5910366.200267436535,
          children: [
            {
              id: 'TRADE_ID|TRADE42739',
              aggregateKey: 'TRADE42739',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部4',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称1',
              tradeId: 'TRADE42739',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 299798.8070753674,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 299798.8070753674,
              initialNotionalAmountTotal: 299798.8070753674,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE47443',
              aggregateKey: 'TRADE47443',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部4',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称6',
              tradeId: 'TRADE47443',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 622042.7128242247,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 622042.7128242247,
              initialNotionalAmountTotal: 622042.7128242247,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE31396',
              aggregateKey: 'TRADE31396',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部3',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称3',
              tradeId: 'TRADE31396',
              tradeStatusName: '存续期',
              initialNotionalAmount: 660457.1623074644,
              subsistingInitialNotionalAmount: 660457.1623074644,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 660457.1623074644,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE24559',
              aggregateKey: 'TRADE24559',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部2',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称6',
              tradeId: 'TRADE24559',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 575911.2886439249,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 575911.2886439249,
              initialNotionalAmountTotal: 575911.2886439249,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE88238',
              aggregateKey: 'TRADE88238',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部6',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称5',
              tradeId: 'TRADE88238',
              tradeStatusName: '存续期',
              initialNotionalAmount: 718065.9823059719,
              subsistingInitialNotionalAmount: 718065.9823059719,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 718065.9823059719,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE62078',
              aggregateKey: 'TRADE62078',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部3',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称2',
              tradeId: 'TRADE62078',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 110237.4692169662,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 110237.4692169662,
              initialNotionalAmountTotal: 110237.4692169662,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE49881',
              aggregateKey: 'TRADE49881',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部2',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称6',
              tradeId: 'TRADE49881',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 33587.807720912075,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 33587.807720912075,
              initialNotionalAmountTotal: 33587.807720912075,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE72970',
              aggregateKey: 'TRADE72970',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部3',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称5',
              tradeId: 'TRADE72970',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 561586.5814899576,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 561586.5814899576,
              initialNotionalAmountTotal: 561586.5814899576,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE43852',
              aggregateKey: 'TRADE43852',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部4',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称3',
              tradeId: 'TRADE43852',
              tradeStatusName: '存续期',
              initialNotionalAmount: 644245.1109316793,
              subsistingInitialNotionalAmount: 644245.1109316793,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 644245.1109316793,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE49814',
              aggregateKey: 'TRADE49814',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部2',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称2',
              tradeId: 'TRADE49814',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 802122.3948169706,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 802122.3948169706,
              initialNotionalAmountTotal: 802122.3948169706,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE43218',
              aggregateKey: 'TRADE43218',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部1',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称5',
              tradeId: 'TRADE43218',
              tradeStatusName: '存续期',
              initialNotionalAmount: 9200.02850595536,
              subsistingInitialNotionalAmount: 9200.02850595536,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 9200.02850595536,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE17446',
              aggregateKey: 'TRADE17446',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部1',
              saleName: '销售1',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称3',
              tradeId: 'TRADE17446',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 873110.8544280421,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 873110.8544280421,
              initialNotionalAmountTotal: 873110.8544280421,
              initialDate: '2022-01-04',
            },
          ],
        },
        {
          id: 'CLIENT_TYPE|结构户',
          aggregateKey: '结构户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 4,
          subsistingInitialNotionalAmount: 4219985.5691411091,
          noSubsistingInitialNotionalAmount: 1450474.721631092567,
          initialNotionalAmountTotal: 5670460.290772201667,
          children: [
            {
              id: 'TRADE_ID|TRADE84775',
              aggregateKey: 'TRADE84775',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部1',
              saleName: '销售1',
              clientType: '结构户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称6',
              tradeId: 'TRADE84775',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 733321.9311938729,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 733321.9311938729,
              initialNotionalAmountTotal: 733321.9311938729,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE65869',
              aggregateKey: 'TRADE65869',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部2',
              saleName: '销售1',
              clientType: '结构户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称4',
              tradeId: 'TRADE65869',
              tradeStatusName: '存续期',
              initialNotionalAmount: 924327.2228483993,
              subsistingInitialNotionalAmount: 924327.2228483993,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 924327.2228483993,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE9993',
              aggregateKey: 'TRADE9993',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部6',
              saleName: '销售1',
              clientType: '结构户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称4',
              tradeId: 'TRADE9993',
              tradeStatusName: '存续期',
              initialNotionalAmount: 591238.6764777025,
              subsistingInitialNotionalAmount: 591238.6764777025,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 591238.6764777025,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE66275',
              aggregateKey: 'TRADE66275',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部3',
              saleName: '销售1',
              clientType: '结构户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称2',
              tradeId: 'TRADE66275',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 712243.7921012855,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 712243.7921012855,
              initialNotionalAmountTotal: 712243.7921012855,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE86189',
              aggregateKey: 'TRADE86189',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部3',
              saleName: '销售1',
              clientType: '结构户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称2',
              tradeId: 'TRADE86189',
              tradeStatusName: '存续期',
              initialNotionalAmount: 612191.8389337696,
              subsistingInitialNotionalAmount: 612191.8389337696,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 612191.8389337696,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE25484',
              aggregateKey: 'TRADE25484',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部4',
              saleName: '销售1',
              clientType: '结构户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称6',
              tradeId: 'TRADE25484',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 4908.998335934167,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 4908.998335934167,
              initialNotionalAmountTotal: 4908.998335934167,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE79328',
              aggregateKey: 'TRADE79328',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部3',
              saleName: '销售1',
              clientType: '结构户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称4',
              tradeId: 'TRADE79328',
              tradeStatusName: '存续期',
              initialNotionalAmount: 653267.5581986762,
              subsistingInitialNotionalAmount: 653267.5581986762,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 653267.5581986762,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE26884',
              aggregateKey: 'TRADE26884',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部4',
              saleName: '销售1',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称4',
              tradeId: 'TRADE26884',
              tradeStatusName: '存续期',
              initialNotionalAmount: 835276.4709534824,
              subsistingInitialNotionalAmount: 835276.4709534824,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 835276.4709534824,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE29007',
              aggregateKey: 'TRADE29007',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部3',
              saleName: '销售1',
              clientType: '结构户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称5',
              tradeId: 'TRADE29007',
              tradeStatusName: '存续期',
              initialNotionalAmount: 603683.8017290791,
              subsistingInitialNotionalAmount: 603683.8017290791,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 603683.8017290791,
              initialDate: '2022-01-04',
            },
          ],
        },
      ],
    },
    {
      id: 'SALE|销售2',
      aggregateKey: '销售2',
      aggregateType: 'SALE',
      aggregateTypeZH: '销售',
      customerNumber: 11,
      subsistingInitialNotionalAmount: 5572673.42290068504,
      noSubsistingInitialNotionalAmount: 4325875.37377591828,
      initialNotionalAmountTotal: 9898548.79667660332,
      children: [
        {
          id: 'CLIENT_TYPE|产品户',
          aggregateKey: '产品户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 6,
          subsistingInitialNotionalAmount: 1367358.43463119408,
          noSubsistingInitialNotionalAmount: 3590109.4942440918,
          initialNotionalAmountTotal: 4957467.92887528588,
          children: [
            {
              id: 'TRADE_ID|TRADE55064',
              aggregateKey: 'TRADE55064',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部4',
              saleName: '销售2',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称3',
              tradeId: 'TRADE55064',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 606069.4540492086,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 606069.4540492086,
              initialNotionalAmountTotal: 606069.4540492086,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE79551',
              aggregateKey: 'TRADE79551',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部2',
              saleName: '销售2',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称1',
              tradeId: 'TRADE79551',
              tradeStatusName: '存续期',
              initialNotionalAmount: 88302.12369935808,
              subsistingInitialNotionalAmount: 88302.12369935808,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 88302.12369935808,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE46287',
              aggregateKey: 'TRADE46287',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部3',
              saleName: '销售2',
              clientType: '产品户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称2',
              tradeId: 'TRADE46287',
              tradeStatusName: '存续期',
              initialNotionalAmount: 914424.4356218748,
              subsistingInitialNotionalAmount: 914424.4356218748,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 914424.4356218748,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE23471',
              aggregateKey: 'TRADE23471',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部3',
              saleName: '销售2',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称4',
              tradeId: 'TRADE23471',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 535848.0460597862,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 535848.0460597862,
              initialNotionalAmountTotal: 535848.0460597862,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE44635',
              aggregateKey: 'TRADE44635',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部4',
              saleName: '销售2',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称6',
              tradeId: 'TRADE44635',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 918446.4087025229,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 918446.4087025229,
              initialNotionalAmountTotal: 918446.4087025229,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE60844',
              aggregateKey: 'TRADE60844',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部2',
              saleName: '销售2',
              clientType: '产品户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称4',
              tradeId: 'TRADE60844',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 829701.610368971,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 829701.610368971,
              initialNotionalAmountTotal: 829701.610368971,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE71977',
              aggregateKey: 'TRADE71977',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部3',
              saleName: '销售2',
              clientType: '产品户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称5',
              tradeId: 'TRADE71977',
              tradeStatusName: '存续期',
              initialNotionalAmount: 364631.8753099612,
              subsistingInitialNotionalAmount: 364631.8753099612,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 364631.8753099612,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE75747',
              aggregateKey: 'TRADE75747',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部1',
              saleName: '销售2',
              clientType: '产品户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称1',
              tradeId: 'TRADE75747',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 700043.9750636031,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 700043.9750636031,
              initialNotionalAmountTotal: 700043.9750636031,
              initialDate: '2022-01-04',
            },
          ],
        },
        {
          id: 'CLIENT_TYPE|结构户',
          aggregateKey: '结构户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 5,
          subsistingInitialNotionalAmount: 4205314.98826949096,
          noSubsistingInitialNotionalAmount: 735765.87953182648,
          initialNotionalAmountTotal: 4941080.86780131744,
          children: [
            {
              id: 'TRADE_ID|TRADE35620',
              aggregateKey: 'TRADE35620',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部6',
              saleName: '销售2',
              clientType: '结构户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称2',
              tradeId: 'TRADE35620',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 242485.19759072718,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 242485.19759072718,
              initialNotionalAmountTotal: 242485.19759072718,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE84341',
              aggregateKey: 'TRADE84341',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部6',
              saleName: '销售2',
              clientType: '结构户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称5',
              tradeId: 'TRADE84341',
              tradeStatusName: '存续期',
              initialNotionalAmount: 887118.5980085649,
              subsistingInitialNotionalAmount: 887118.5980085649,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 887118.5980085649,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE13706',
              aggregateKey: 'TRADE13706',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部2',
              saleName: '销售2',
              clientType: '结构户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称2',
              tradeId: 'TRADE13706',
              tradeStatusName: '存续期',
              initialNotionalAmount: 365963.9125857732,
              subsistingInitialNotionalAmount: 365963.9125857732,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 365963.9125857732,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE23193',
              aggregateKey: 'TRADE23193',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部1',
              saleName: '销售2',
              clientType: '结构户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称6',
              tradeId: 'TRADE23193',
              tradeStatusName: '存续期',
              initialNotionalAmount: 950995.7816842359,
              subsistingInitialNotionalAmount: 950995.7816842359,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 950995.7816842359,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE71109',
              aggregateKey: 'TRADE71109',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部6',
              saleName: '销售2',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称3',
              tradeId: 'TRADE71109',
              tradeStatusName: '存续期',
              initialNotionalAmount: 985543.4327692642,
              subsistingInitialNotionalAmount: 985543.4327692642,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 985543.4327692642,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE4884',
              aggregateKey: 'TRADE4884',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部1',
              saleName: '销售2',
              clientType: '结构户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称1',
              tradeId: 'TRADE4884',
              tradeStatusName: '存续期',
              initialNotionalAmount: 934626.9243385773,
              subsistingInitialNotionalAmount: 934626.9243385773,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 934626.9243385773,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE60702',
              aggregateKey: 'TRADE60702',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部4',
              saleName: '销售2',
              clientType: '结构户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称3',
              tradeId: 'TRADE60702',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 493280.6819410993,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 493280.6819410993,
              initialNotionalAmountTotal: 493280.6819410993,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE29579',
              aggregateKey: 'TRADE29579',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部6',
              saleName: '销售2',
              clientType: '结构户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称6',
              tradeId: 'TRADE29579',
              tradeStatusName: '存续期',
              initialNotionalAmount: 81066.33888307546,
              subsistingInitialNotionalAmount: 81066.33888307546,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 81066.33888307546,
              initialDate: '2022-01-04',
            },
          ],
        },
      ],
    },
    {
      id: 'SALE|销售3',
      aggregateKey: '销售3',
      aggregateType: 'SALE',
      aggregateTypeZH: '销售',
      customerNumber: 8,
      subsistingInitialNotionalAmount: 3547766.82169367383,
      noSubsistingInitialNotionalAmount: 5033062.293038696198,
      initialNotionalAmountTotal: 8580829.114732370028,
      children: [
        {
          id: 'CLIENT_TYPE|产品户',
          aggregateKey: '产品户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 4,
          subsistingInitialNotionalAmount: 1325774.49460383123,
          noSubsistingInitialNotionalAmount: 2850103.171947775538,
          initialNotionalAmountTotal: 4175877.666551606768,
          children: [
            {
              id: 'TRADE_ID|TRADE24227',
              aggregateKey: 'TRADE24227',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部6',
              saleName: '销售3',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称3',
              tradeId: 'TRADE24227',
              tradeStatusName: '存续期',
              initialNotionalAmount: 251213.03976590803,
              subsistingInitialNotionalAmount: 251213.03976590803,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 251213.03976590803,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE30285',
              aggregateKey: 'TRADE30285',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部4',
              saleName: '销售3',
              clientType: '产品户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称2',
              tradeId: 'TRADE30285',
              tradeStatusName: '存续期',
              initialNotionalAmount: 434657.0338287017,
              subsistingInitialNotionalAmount: 434657.0338287017,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 434657.0338287017,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE59238',
              aggregateKey: 'TRADE59238',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部4',
              saleName: '销售3',
              clientType: '产品户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称3',
              tradeId: 'TRADE59238',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 507089.0310048715,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 507089.0310048715,
              initialNotionalAmountTotal: 507089.0310048715,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE69455',
              aggregateKey: 'TRADE69455',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部2',
              saleName: '销售3',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称2',
              tradeId: 'TRADE69455',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 545687.785692418,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 545687.785692418,
              initialNotionalAmountTotal: 545687.785692418,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE56568',
              aggregateKey: 'TRADE56568',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部1',
              saleName: '销售3',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称4',
              tradeId: 'TRADE56568',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 3252.564201263408,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 3252.564201263408,
              initialNotionalAmountTotal: 3252.564201263408,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE40410',
              aggregateKey: 'TRADE40410',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部1',
              saleName: '销售3',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称3',
              tradeId: 'TRADE40410',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 442234.04479098413,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 442234.04479098413,
              initialNotionalAmountTotal: 442234.04479098413,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE16865',
              aggregateKey: 'TRADE16865',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部3',
              saleName: '销售3',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称1',
              tradeId: 'TRADE16865',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 262023.6670935966,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 262023.6670935966,
              initialNotionalAmountTotal: 262023.6670935966,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE29425',
              aggregateKey: 'TRADE29425',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部2',
              saleName: '销售3',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称3',
              tradeId: 'TRADE29425',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 523600.673533397,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 523600.673533397,
              initialNotionalAmountTotal: 523600.673533397,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE34303',
              aggregateKey: 'TRADE34303',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部1',
              saleName: '销售3',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称2',
              tradeId: 'TRADE34303',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 566215.4056312449,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 566215.4056312449,
              initialNotionalAmountTotal: 566215.4056312449,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE81922',
              aggregateKey: 'TRADE81922',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部1',
              saleName: '销售3',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称3',
              tradeId: 'TRADE81922',
              tradeStatusName: '存续期',
              initialNotionalAmount: 639904.4210092215,
              subsistingInitialNotionalAmount: 639904.4210092215,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 639904.4210092215,
              initialDate: '2022-01-04',
            },
          ],
        },
        {
          id: 'CLIENT_TYPE|结构户',
          aggregateKey: '结构户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 4,
          subsistingInitialNotionalAmount: 2221992.3270898426,
          noSubsistingInitialNotionalAmount: 2182959.12109092066,
          initialNotionalAmountTotal: 4404951.44818076326,
          children: [
            {
              id: 'TRADE_ID|TRADE58214',
              aggregateKey: 'TRADE58214',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部1',
              saleName: '销售3',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称3',
              tradeId: 'TRADE58214',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 954284.8946045847,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 954284.8946045847,
              initialNotionalAmountTotal: 954284.8946045847,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE95067',
              aggregateKey: 'TRADE95067',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部6',
              saleName: '销售3',
              clientType: '结构户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称2',
              tradeId: 'TRADE95067',
              tradeStatusName: '存续期',
              initialNotionalAmount: 705602.8421641157,
              subsistingInitialNotionalAmount: 705602.8421641157,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 705602.8421641157,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE73134',
              aggregateKey: 'TRADE73134',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部5',
              saleName: '销售3',
              clientType: '结构户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称4',
              tradeId: 'TRADE73134',
              tradeStatusName: '存续期',
              initialNotionalAmount: 727490.4396241946,
              subsistingInitialNotionalAmount: 727490.4396241946,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 727490.4396241946,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE69325',
              aggregateKey: 'TRADE69325',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部5',
              saleName: '销售3',
              clientType: '结构户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称6',
              tradeId: 'TRADE69325',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 481547.89423117816,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 481547.89423117816,
              initialNotionalAmountTotal: 481547.89423117816,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE50398',
              aggregateKey: 'TRADE50398',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部2',
              saleName: '销售3',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称4',
              tradeId: 'TRADE50398',
              tradeStatusName: '存续期',
              initialNotionalAmount: 788899.0453015323,
              subsistingInitialNotionalAmount: 788899.0453015323,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 788899.0453015323,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE86538',
              aggregateKey: 'TRADE86538',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部5',
              saleName: '销售3',
              clientType: '结构户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称3',
              tradeId: 'TRADE86538',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 384160.0707845445,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 384160.0707845445,
              initialNotionalAmountTotal: 384160.0707845445,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE52316',
              aggregateKey: 'TRADE52316',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部5',
              saleName: '销售3',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称6',
              tradeId: 'TRADE52316',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 362966.2614706133,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 362966.2614706133,
              initialNotionalAmountTotal: 362966.2614706133,
              initialDate: '2022-01-04',
            },
          ],
        },
      ],
    },
    {
      id: 'SALE|销售4',
      aggregateKey: '销售4',
      aggregateType: 'SALE',
      aggregateTypeZH: '销售',
      customerNumber: 8,
      subsistingInitialNotionalAmount: 3742385.27659492676,
      noSubsistingInitialNotionalAmount: 1211896.263610726,
      initialNotionalAmountTotal: 4954281.54020565276,
      children: [
        {
          id: 'CLIENT_TYPE|产品户',
          aggregateKey: '产品户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 4,
          subsistingInitialNotionalAmount: 2643128.8424734855,
          noSubsistingInitialNotionalAmount: 401760.1110035031,
          initialNotionalAmountTotal: 3044888.9534769886,
          children: [
            {
              id: 'TRADE_ID|TRADE21471',
              aggregateKey: 'TRADE21471',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部4',
              saleName: '销售4',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称1',
              tradeId: 'TRADE21471',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 401760.1110035031,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 401760.1110035031,
              initialNotionalAmountTotal: 401760.1110035031,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE78387',
              aggregateKey: 'TRADE78387',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部1',
              saleName: '销售4',
              clientType: '产品户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称5',
              tradeId: 'TRADE78387',
              tradeStatusName: '存续期',
              initialNotionalAmount: 633390.996309439,
              subsistingInitialNotionalAmount: 633390.996309439,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 633390.996309439,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE33681',
              aggregateKey: 'TRADE33681',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部3',
              saleName: '销售4',
              clientType: '产品户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称5',
              tradeId: 'TRADE33681',
              tradeStatusName: '存续期',
              initialNotionalAmount: 418176.86375475803,
              subsistingInitialNotionalAmount: 418176.86375475803,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 418176.86375475803,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE87883',
              aggregateKey: 'TRADE87883',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部3',
              saleName: '销售4',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称5',
              tradeId: 'TRADE87883',
              tradeStatusName: '存续期',
              initialNotionalAmount: 93803.10344451104,
              subsistingInitialNotionalAmount: 93803.10344451104,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 93803.10344451104,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE89136',
              aggregateKey: 'TRADE89136',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部2',
              saleName: '销售4',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称3',
              tradeId: 'TRADE89136',
              tradeStatusName: '存续期',
              initialNotionalAmount: 463859.31636253063,
              subsistingInitialNotionalAmount: 463859.31636253063,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 463859.31636253063,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE65437',
              aggregateKey: 'TRADE65437',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部6',
              saleName: '销售4',
              clientType: '产品户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称6',
              tradeId: 'TRADE65437',
              tradeStatusName: '存续期',
              initialNotionalAmount: 634365.5159522013,
              subsistingInitialNotionalAmount: 634365.5159522013,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 634365.5159522013,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE26931',
              aggregateKey: 'TRADE26931',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部6',
              saleName: '销售4',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称6',
              tradeId: 'TRADE26931',
              tradeStatusName: '存续期',
              initialNotionalAmount: 399533.0466500455,
              subsistingInitialNotionalAmount: 399533.0466500455,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 399533.0466500455,
              initialDate: '2022-01-04',
            },
          ],
        },
        {
          id: 'CLIENT_TYPE|结构户',
          aggregateKey: '结构户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 4,
          subsistingInitialNotionalAmount: 1099256.43412144126,
          noSubsistingInitialNotionalAmount: 810136.1526072229,
          initialNotionalAmountTotal: 1909392.58672866416,
          children: [
            {
              id: 'TRADE_ID|TRADE33351',
              aggregateKey: 'TRADE33351',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部1',
              saleName: '销售4',
              clientType: '结构户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称6',
              tradeId: 'TRADE33351',
              tradeStatusName: '存续期',
              initialNotionalAmount: 146811.52895205817,
              subsistingInitialNotionalAmount: 146811.52895205817,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 146811.52895205817,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE16426',
              aggregateKey: 'TRADE16426',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部6',
              saleName: '销售4',
              clientType: '结构户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称1',
              tradeId: 'TRADE16426',
              tradeStatusName: '存续期',
              initialNotionalAmount: 294129.4063566833,
              subsistingInitialNotionalAmount: 294129.4063566833,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 294129.4063566833,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE11001',
              aggregateKey: 'TRADE11001',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部6',
              saleName: '销售4',
              clientType: '结构户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称6',
              tradeId: 'TRADE11001',
              tradeStatusName: '存续期',
              initialNotionalAmount: 215902.99547641934,
              subsistingInitialNotionalAmount: 215902.99547641934,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 215902.99547641934,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE38678',
              aggregateKey: 'TRADE38678',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部5',
              saleName: '销售4',
              clientType: '结构户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称4',
              tradeId: 'TRADE38678',
              tradeStatusName: '存续期',
              initialNotionalAmount: 409501.47849698114,
              subsistingInitialNotionalAmount: 409501.47849698114,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 409501.47849698114,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE60996',
              aggregateKey: 'TRADE60996',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部5',
              saleName: '销售4',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称5',
              tradeId: 'TRADE60996',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 810136.1526072229,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 810136.1526072229,
              initialNotionalAmountTotal: 810136.1526072229,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE41775',
              aggregateKey: 'TRADE41775',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部1',
              saleName: '销售4',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称5',
              tradeId: 'TRADE41775',
              tradeStatusName: '存续期',
              initialNotionalAmount: 32911.02483929931,
              subsistingInitialNotionalAmount: 32911.02483929931,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 32911.02483929931,
              initialDate: '2022-01-04',
            },
          ],
        },
      ],
    },
    {
      id: 'SALE|销售5',
      aggregateKey: '销售5',
      aggregateType: 'SALE',
      aggregateTypeZH: '销售',
      customerNumber: 7,
      subsistingInitialNotionalAmount: 4301452.23536431785,
      noSubsistingInitialNotionalAmount: 1685077.862715789815,
      initialNotionalAmountTotal: 5986530.098080107665,
      children: [
        {
          id: 'CLIENT_TYPE|产品户',
          aggregateKey: '产品户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 4,
          subsistingInitialNotionalAmount: 1013128.80906463635,
          noSubsistingInitialNotionalAmount: 872782.938167603215,
          initialNotionalAmountTotal: 1885911.747232239565,
          children: [
            {
              id: 'TRADE_ID|TRADE25943',
              aggregateKey: 'TRADE25943',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部6',
              saleName: '销售5',
              clientType: '产品户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称1',
              tradeId: 'TRADE25943',
              tradeStatusName: '存续期',
              initialNotionalAmount: 228211.11659196625,
              subsistingInitialNotionalAmount: 228211.11659196625,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 228211.11659196625,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE40768',
              aggregateKey: 'TRADE40768',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部2',
              saleName: '销售5',
              clientType: '产品户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称2',
              tradeId: 'TRADE40768',
              tradeStatusName: '存续期',
              initialNotionalAmount: 271574.2057137858,
              subsistingInitialNotionalAmount: 271574.2057137858,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 271574.2057137858,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE14193',
              aggregateKey: 'TRADE14193',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部4',
              saleName: '销售5',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称2',
              tradeId: 'TRADE14193',
              tradeStatusName: '存续期',
              initialNotionalAmount: 513343.4867588843,
              subsistingInitialNotionalAmount: 513343.4867588843,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 513343.4867588843,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE83772',
              aggregateKey: 'TRADE83772',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部2',
              saleName: '销售5',
              clientType: '产品户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称4',
              tradeId: 'TRADE83772',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 14387.534060592345,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 14387.534060592345,
              initialNotionalAmountTotal: 14387.534060592345,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE98640',
              aggregateKey: 'TRADE98640',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部3',
              saleName: '销售5',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称1',
              tradeId: 'TRADE98640',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 292312.88715723134,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 292312.88715723134,
              initialNotionalAmountTotal: 292312.88715723134,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE68926',
              aggregateKey: 'TRADE68926',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部5',
              saleName: '销售5',
              clientType: '产品户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称4',
              tradeId: 'TRADE68926',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 109870.05551880447,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 109870.05551880447,
              initialNotionalAmountTotal: 109870.05551880447,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE63205',
              aggregateKey: 'TRADE63205',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部1',
              saleName: '销售5',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称5',
              tradeId: 'TRADE63205',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 456212.46143097506,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 456212.46143097506,
              initialNotionalAmountTotal: 456212.46143097506,
              initialDate: '2022-01-04',
            },
          ],
        },
        {
          id: 'CLIENT_TYPE|结构户',
          aggregateKey: '结构户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 3,
          subsistingInitialNotionalAmount: 3288323.4262996815,
          noSubsistingInitialNotionalAmount: 812294.9245481866,
          initialNotionalAmountTotal: 4100618.3508478681,
          children: [
            {
              id: 'TRADE_ID|TRADE3026',
              aggregateKey: 'TRADE3026',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部4',
              saleName: '销售5',
              clientType: '结构户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称1',
              tradeId: 'TRADE3026',
              tradeStatusName: '存续期',
              initialNotionalAmount: 902241.3780598573,
              subsistingInitialNotionalAmount: 902241.3780598573,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 902241.3780598573,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE49782',
              aggregateKey: 'TRADE49782',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部1',
              saleName: '销售5',
              clientType: '结构户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称2',
              tradeId: 'TRADE49782',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 620278.3462364718,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 620278.3462364718,
              initialNotionalAmountTotal: 620278.3462364718,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE15674',
              aggregateKey: 'TRADE15674',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部1',
              saleName: '销售5',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称4',
              tradeId: 'TRADE15674',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 192016.5783117148,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 192016.5783117148,
              initialNotionalAmountTotal: 192016.5783117148,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE46937',
              aggregateKey: 'TRADE46937',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部2',
              saleName: '销售5',
              clientType: '结构户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称1',
              tradeId: 'TRADE46937',
              tradeStatusName: '存续期',
              initialNotionalAmount: 760847.0378627102,
              subsistingInitialNotionalAmount: 760847.0378627102,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 760847.0378627102,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE27521',
              aggregateKey: 'TRADE27521',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部1',
              saleName: '销售5',
              clientType: '结构户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称1',
              tradeId: 'TRADE27521',
              tradeStatusName: '存续期',
              initialNotionalAmount: 799805.3867650764,
              subsistingInitialNotionalAmount: 799805.3867650764,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 799805.3867650764,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE52963',
              aggregateKey: 'TRADE52963',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部6',
              saleName: '销售5',
              clientType: '结构户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称2',
              tradeId: 'TRADE52963',
              tradeStatusName: '存续期',
              initialNotionalAmount: 825429.6236120376,
              subsistingInitialNotionalAmount: 825429.6236120376,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 825429.6236120376,
              initialDate: '2022-01-04',
            },
          ],
        },
      ],
    },
    {
      id: 'SALE|销售6',
      aggregateKey: '销售6',
      aggregateType: 'SALE',
      aggregateTypeZH: '销售',
      customerNumber: 9,
      subsistingInitialNotionalAmount: 5288695.108701714694,
      noSubsistingInitialNotionalAmount: 4426469.96447954858,
      initialNotionalAmountTotal: 9715165.073181263274,
      children: [
        {
          id: 'CLIENT_TYPE|产品户',
          aggregateKey: '产品户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 4,
          subsistingInitialNotionalAmount: 1265557.047661069374,
          noSubsistingInitialNotionalAmount: 1412582.71022805108,
          initialNotionalAmountTotal: 2678139.757889120454,
          children: [
            {
              id: 'TRADE_ID|TRADE19592',
              aggregateKey: 'TRADE19592',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部5',
              saleName: '销售6',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称2',
              tradeId: 'TRADE19592',
              tradeStatusName: '存续期',
              initialNotionalAmount: 169870.87106189935,
              subsistingInitialNotionalAmount: 169870.87106189935,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 169870.87106189935,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE58001',
              aggregateKey: 'TRADE58001',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部2',
              saleName: '销售6',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称3',
              tradeId: 'TRADE58001',
              tradeStatusName: '存续期',
              initialNotionalAmount: 783732.7930061249,
              subsistingInitialNotionalAmount: 783732.7930061249,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 783732.7930061249,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE60373',
              aggregateKey: 'TRADE60373',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部1',
              saleName: '销售6',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称4',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称4',
              tradeId: 'TRADE60373',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 171685.82895722374,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 171685.82895722374,
              initialNotionalAmountTotal: 171685.82895722374,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE39762',
              aggregateKey: 'TRADE39762',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部5',
              saleName: '销售6',
              clientType: '产品户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称1',
              tradeId: 'TRADE39762',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 357233.5078333668,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 357233.5078333668,
              initialNotionalAmountTotal: 357233.5078333668,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE36947',
              aggregateKey: 'TRADE36947',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部1',
              saleName: '销售6',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称2',
              tradeId: 'TRADE36947',
              tradeStatusName: '存续期',
              initialNotionalAmount: 12910.713606653524,
              subsistingInitialNotionalAmount: 12910.713606653524,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 12910.713606653524,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE46448',
              aggregateKey: 'TRADE46448',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部5',
              saleName: '销售6',
              clientType: '产品户',
              businessType: '业务类型5',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称3',
              tradeId: 'TRADE46448',
              tradeStatusName: '存续期',
              initialNotionalAmount: 299042.6699863916,
              subsistingInitialNotionalAmount: 299042.6699863916,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 299042.6699863916,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE85803',
              aggregateKey: 'TRADE85803',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部2',
              saleName: '销售6',
              clientType: '产品户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称4',
              tradeId: 'TRADE85803',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 784704.8737043119,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 784704.8737043119,
              initialNotionalAmountTotal: 784704.8737043119,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE41610',
              aggregateKey: 'TRADE41610',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部2',
              saleName: '销售6',
              clientType: '产品户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称1',
              tradeId: 'TRADE41610',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 98958.49973314864,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 98958.49973314864,
              initialNotionalAmountTotal: 98958.49973314864,
              initialDate: '2022-01-04',
            },
          ],
        },
        {
          id: 'CLIENT_TYPE|结构户',
          aggregateKey: '结构户',
          aggregateType: 'CLIENT_TYPE',
          aggregateTypeZH: '交易对手类型',
          customerNumber: 5,
          subsistingInitialNotionalAmount: 4023138.06104064532,
          noSubsistingInitialNotionalAmount: 3013887.2542514975,
          initialNotionalAmountTotal: 7037025.31529214282,
          children: [
            {
              id: 'TRADE_ID|TRADE73754',
              aggregateKey: 'TRADE73754',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部5',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型1',
              partyName: '交易对手名称3',
              tradeId: 'TRADE73754',
              tradeStatusName: '存续期',
              initialNotionalAmount: 735488.892595752,
              subsistingInitialNotionalAmount: 735488.892595752,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 735488.892595752,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE50822',
              aggregateKey: 'TRADE50822',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部6',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称2',
              tradeId: 'TRADE50822',
              tradeStatusName: '存续期',
              initialNotionalAmount: 955317.6808782065,
              subsistingInitialNotionalAmount: 955317.6808782065,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 955317.6808782065,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE13138',
              aggregateKey: 'TRADE13138',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司1',
              branchName: '营业部4',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称2',
              tradeId: 'TRADE13138',
              tradeStatusName: '存续期',
              initialNotionalAmount: 633466.5702326952,
              subsistingInitialNotionalAmount: 633466.5702326952,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 633466.5702326952,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE86135',
              aggregateKey: 'TRADE86135',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部2',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称3',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称6',
              tradeId: 'TRADE86135',
              tradeStatusName: '存续期',
              initialNotionalAmount: 728087.6145118076,
              subsistingInitialNotionalAmount: 728087.6145118076,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 728087.6145118076,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE28654',
              aggregateKey: 'TRADE28654',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部6',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型3',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称1',
              tradeId: 'TRADE28654',
              tradeStatusName: '存续期',
              initialNotionalAmount: 126182.98010827412,
              subsistingInitialNotionalAmount: 126182.98010827412,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 126182.98010827412,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE5343',
              aggregateKey: 'TRADE5343',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部2',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型4',
              partyName: '交易对手名称6',
              tradeId: 'TRADE5343',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 991801.9102560006,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 991801.9102560006,
              initialNotionalAmountTotal: 991801.9102560006,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE39773',
              aggregateKey: 'TRADE39773',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司3',
              branchName: '营业部3',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称4',
              tradeId: 'TRADE39773',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 423921.702121589,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 423921.702121589,
              initialNotionalAmountTotal: 423921.702121589,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE8127',
              aggregateKey: 'TRADE8127',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司2',
              branchName: '营业部3',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称6',
              entityType: '机构或产品类型2',
              partyName: '交易对手名称2',
              tradeId: 'TRADE8127',
              tradeStatusName: '存续期',
              initialNotionalAmount: 307220.222076814,
              subsistingInitialNotionalAmount: 307220.222076814,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 307220.222076814,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE85708',
              aggregateKey: 'TRADE85708',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司6',
              branchName: '营业部1',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型1',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称6',
              tradeId: 'TRADE85708',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 612862.4849520377,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 612862.4849520377,
              initialNotionalAmountTotal: 612862.4849520377,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE33204',
              aggregateKey: 'TRADE33204',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部2',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型4',
              businessTypeName: '业务类型名称1',
              entityType: '机构或产品类型5',
              partyName: '交易对手名称2',
              tradeId: 'TRADE33204',
              tradeStatusName: '存续期',
              initialNotionalAmount: 537374.1006370959,
              subsistingInitialNotionalAmount: 537374.1006370959,
              noSubsistingInitialNotionalAmount: 0,
              initialNotionalAmountTotal: 537374.1006370959,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE26402',
              aggregateKey: 'TRADE26402',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司5',
              branchName: '营业部6',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型2',
              businessTypeName: '业务类型名称2',
              entityType: '机构或产品类型3',
              partyName: '交易对手名称1',
              tradeId: 'TRADE26402',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 564982.9313668688,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 564982.9313668688,
              initialNotionalAmountTotal: 564982.9313668688,
              initialDate: '2022-01-04',
            },
            {
              id: 'TRADE_ID|TRADE27744',
              aggregateKey: 'TRADE27744',
              aggregateType: 'TRADE_ID',
              aggregateTypeZH: '交易ID',
              subsidiaryName: '分公司4',
              branchName: '营业部4',
              saleName: '销售6',
              clientType: '结构户',
              businessType: '业务类型6',
              businessTypeName: '业务类型名称5',
              entityType: '机构或产品类型6',
              partyName: '交易对手名称2',
              tradeId: 'TRADE27744',
              tradeStatusName: '非存续期',
              initialNotionalAmount: 420318.2255550014,
              subsistingInitialNotionalAmount: 0,
              noSubsistingInitialNotionalAmount: 420318.2255550014,
              initialNotionalAmountTotal: 420318.2255550014,
              initialDate: '2022-01-04',
            },
          ],
        },
      ],
    },
  ],
};
