enum SwapFieldNameEnums {
  /** 操作列 */
  TableAction = 'tableAction',
  /** 标的物信息 */
  TargetInfo = 'targetInfo',
  /** 合约详情 */
  ContractInfo = 'contractInfo',
  /** 结算金额 */
  SettleAmountInfo = 'settleAmountInfo',
  /** 结算金额(结算货币) */
  SettleCurrencySettleAmountInfo = 'settleCurrencySettleAmountInfo',
  /** 对手方名称 */
  CounterPartyName = 'counterPartyName',
  /** 交易对手SAC编号 */
  MasterAgreementId = 'masterAgreementId',
  /** 多头/空头-开/平仓交易费率 */
  EarlyTerminationRate = 'earlyTerminationRate',
  /** 预付金返息利率 */
  AdvanceFeeReturnRate = 'advanceFeeReturnRate',
  /** bookName */
  BookName = 'bookName',
  /** 合约编号 */
  ContractCode = 'contractCode',
  /** 交易确认书编号 */
  TradeConfirmId = 'tradeConfirmId',
  /** 交易方向 */
  ContractDirection = 'contractDirection',
  /** 互换类型 */
  SwapProductType = 'swapProductType',
  /** 合约期初名义本金额 */
  ContractInitNotionalAmount = 'contractInitNotionalAmount',
  /** 交易达成日 */
  TradeDate = 'tradeDate',
  /** 起始日 */
  EffectiveDate = 'effectiveDate',
  /** 结算日 */
  SettlementDate = 'settlementDate',
  /** 期末观察日 */
  ExpirationDate = 'expirationDate',
  /** 利率收益支付频率 */
  InterestPayFrequency = 'interestPayFrequency',
  /** 增强收益支付频率 */
  EnhancedPayFrequency = 'enhancedPayFrequency',
  /** 利率收益计息方式 */
  SettlementMethod = 'settlementMethod',
  /** 增强收益计息方式 */
  EnhancedPeriodCountConvention = 'enhancedPeriodCountConvention',
  /** 增强收益计息截止日 */
  EnhancedIncomeDeadLine = 'enhancedIncomeDeadLine',
  /** 年化天数 */
  DaysInYear = 'daysInYear',
  /** 基本费率 */
  BaseRate = 'baseRate',
  /** 空头计息基准 */
  ShortSideInterestAccrualReference = 'shortSideInterestAccrualReference',
  /** 多头约定固定利率 */
  LongSideFixRate = 'longSideFixRate',
  /** 多头约定浮动利率基准 */
  LongSideFloatIndex = 'longSideFloatIndex',
  /** 空头约定浮动利率基准 */
  ShortSideFloatIndex = 'shortSideFloatIndex',
  // 权益段
  /** 多头/空头组合名义本金额 */
  SideTotalNotionalAmount = 'SideTotalNotionalAmount',
  /** 标的代码 */
  UnderlyingInstrumentId = 'underlyingInstrumentId',
  /** 标的简称 */
  UnderlyingInstrumentSimpleName = 'underlyingInstrumentSimpleName',
  /** 折算率 */
  ConversionRate = 'conversionRate',
  /** 标的开仓方向 */
  EquityDirection = 'equityDirection',
  /** 全收益指数 */
  TotalReturnIndex = 'totalReturnIndex',
  /** 标的期初价格 */
  InitSpot = 'initSpot',
  /** 成本价格 */
  CostSpot = 'costSpot',
  /** 标的期初名义数量（手） */
  InitAmount = 'initAmount',
  /** 标的乘数 */
  Multiplier = 'multiplier',
  /** 标的股息分派比例 */
  DividendRate = 'dividendRate',
  /** 标的估值价格类型 */
  EvaluationQuoteType = 'evaluationQuoteType',
  /** 标的期初名义本金额 */
  EquityInitNotionalAmount = 'equityInitNotionalAmount',
  /** 标的期初名义本金额(持仓) */
  InitNotionalAmount = 'initNotionalAmount',
  /** 多头约定固定利率 */
  /** 多头约定浮动利率 弹窗多个字段 */
  LongSideFloatRates = 'longSideFloatRates',
  /** 观察日与作用起始日间隔 */
  Interval = 'interval',
  /** 利率作用频率 */
  RatesFrequency = 'ratesFrequency',
  /** 计息截止日类别 */
  InterestIncomeDeadLine = 'interestIncomeDeadLine',
  /** 多头约定浮动利率 弹窗里 表格字段 */
  LongSideFloatRatesTable = 'LongSideFloatRatesTable',

  /** 观察频率 */
  FixingFrequency = 'fixingFrequency',
  /** 观察日 */
  FixingDate = 'fixingDate',
  /** 多头约定浮动利率 */
  Rate = 'rate',
  /** 增强收益率 弹窗多个字段 */
  EnhancedRate = 'enhancedRate',
  // 保障金
  /** 多头初始保障比例参数 */
  LongSideInitialMarginRatio = 'longSideInitialMarginRatio',
  /** 空头初始保障比例参数 */
  ShortSideInitialMarginRatio = 'shortSideInitialMarginRatio',
  /** 多头维持保障比例参数 */
  LongSideMaintenanceMarginRatio = 'longSideMaintenanceMarginRatio',
  /** 空头维持保障比例参数 */
  ShortSideMaintenanceMarginRatio = 'shortSideMaintenanceMarginRatio',
  /** 追加后保障比例参数 */
  AdditionalMarginRatio = 'additionalMarginRatio',
  /** 多头盯市基准 */
  LongSideMtmReference = 'longSideMtmReference',
  /** 空头盯市基准 */
  ShortSideMtmReference = 'shortSideMtmReference',
  /** 初始预付金金额 */
  ContractInitialMarginAmount = 'contractInitialMarginAmount',

  /** 公共字段 */
  /** 约定浮动利率 */
  SideFloatRates = 'SideFloatRates',
  /** 约定固定利率 */
  SideFixRate = 'SideFixRate',
  /** 约定浮动费率基准 */
  SideFloatIndex = 'SideFloatIndex',
  /** 约定浮动利率 */
  /** 作用起始日 */
  ActiveDate = 'activeDate',
  /** 作用截止日 */
  DurabilityDate = 'durabilityDate',

  /** 权益相关 */
  Legs = 'legs',

  /** 约定固定利率 */
  FixRate = 'fixRate',

  /** 约定浮动利率基准 */
  FloatIndex = 'floatIndex',
  /** 约定浮动利率 */
  FloatRates = 'floatRates',
  /** 增强收益率 */
  EnhanceRates = 'enhanceRates',

  /** 增强收益率表格数据 */
  EnhanceRatesTable = 'enhanceRatesTable',
  FloatRatesTable = 'floatRatesTable',
  /** 合约期初名义本金 */
  ContractNotionalAmount = 'contractNotionalAmount',

  /** 标的合约本金 */
  NotionalAmount = 'notionalAmount',
  PeriodCountConvention = 'periodCountConvention',
  /** 标的开仓方向 */
  SwapDirection = 'swapDirection',
  /** 计息起始日 */
  StartDate = 'startDate',
  EndDate = 'endDate',
  /** 支付日期 */
  PaymentDate = 'paymentDate',
  Comment = 'comment',
  Sale = 'sale',
  /** 合约状态 */
  ContractStatus = 'contractStatus',
  /** 持仓状态 */
  PositionStatus = 'positionStatus',
  /** 生效日期 */
  AvailableDate = 'availableDate',
  /** 新限制多头名义本金额 */
  FreezeNotionalAmount = 'freezeNotionalAmount',
  /** 解除限制多头名义本金额 */
  UnfreezeNotionalAmount = 'unfreezeNotionalAmount',
  /** 多头限制期名义本金额 */
  LongSideLimitNotionalAmount = 'longSideLimitNotionalAmount',
  /** 未实现单位股息(￥) */
  Dividends = 'dividends',
  /** 存续名义数量(名义数量(股/张/手)) */
  TargetAmount = 'targetAmount',
  /** 未实现股息 */
  TotalAmount = 'totalAmount',
  /** 到期结算标的详情 */
  SettlementTargetInfo = 'settlementTargetInfo',
  /** 结算数量（股/张/手） */
  SettleAmount = 'settleAmount',
  /** 期末价格 */
  SettlePrice = 'settlePrice',
  /** 权益收益 */
  EquityIncome = 'equityIncome',
  /** 实现单位股息 */
  RealizeUnitDividends = 'realizeUnitDividends',
  /** 实现股息金额 */
  RealizeDividends = 'realizeDividends',
  /** 总实现合约权益收益(￥) */
  TotalEquityIncome = 'totalEquityIncome',
  /** 实现合约权益收益.股息(￥) */
  TotalRealizeDividends = 'totalRealizeDividends',
  /** 实现合约利率收益(￥) */
  TotalInterestIncome = 'totalInterestIncome',
  /** 支付金额(￥) */
  Cashflow = 'cashflow',
  /** 平仓日期 */
  UnwindDate = 'unwindDate',
  /** 平仓数量 */
  UnwindAmount = 'unwindAmount',
  /** 平仓价格 */
  UnwindPrice = 'unwindPrice',
  /** 平仓(结算)名义本金额 */
  SettleNotionalAmount = 'settleNotionalAmount',
  /** 多头名义本金额 */
  LongNominalPrincipalAmount = 'longNominalPrincipalAmount',
  /** 提取前保障比例参数 */
  BeforeWithdrawalMarginRatio = 'beforeWithdrawalMarginRatio',
  /** 提取后保障比例参数 */
  AfterWithdrawalMarginRatio = 'afterWithdrawalMarginRatio',
  /** 多头限制约定费率 */
  LongSideLimitRates = 'longSideLimitRates',
  /** 多头约定费率 */
  LongSideTotalRates = 'longSideTotalRates',
  /** 标的名义数量 */
  Amount = 'amount',
  /** 多头计息基准 */
  LongSideInterestAccrualReference = 'longSideInterestAccrualReference',
  /** 多头约定费率计息基准 */
  LongSideInterestAccrualAmount = 'longSideInterestAccrualAmount',
  /** 合约期初名义本金额 */
  InitContractNotionalAmount = 'initContractNotionalAmount',
  /** 持仓标的方向 */
  LongShort = 'longShort',
  /** 操作用户 用户名 */
  UserName = 'userName',
  ExecutionTime = 'executionTime',
  /** 生命周期事件类型 */
  EventType = 'eventType',
  /** 操作用户 */
  ExecUser = 'execUser',
  ExecDate = 'execDate',
  LcmEventType = 'lcmEventType',
  /** 操作时间 */
  ExecDateTime = 'execDateTime',
  /** 估值日 */
  ValuationDate = 'valuationDate',
  /** 估值价格 */
  EvaluatePrice = 'evaluatePrice',
  /** 累计平仓/结算数量 */
  AccumulateSettleAmount = 'accumulateSettleAmount',
  /** 标的名义本金额 */
  CurrentNotionalAmount = 'currentNotionalAmount',
  /** 标的市值 */
  MarketValue = 'marketValue',
  /** 平仓/结算 当日实现权益收益 */
  NewlyRealizedCashFlow = 'newlyRealizedCashFlow',
  /** 指数增强收益 */
  EnhanceIndexIncome = 'enhanceIndexIncome',
  /** 待实现权益收益 */
  UnrealizedCashFlow = 'unrealizedCashFlow',
  /** 约定费率 */
  AgreedInterestRate = 'agreedInterestRate',
  /** 计息基准 */
  AccrualReference = 'accrualReference',
  /** 约定费率计息基准 */
  AccrualAmount = 'accrualAmount',
  /** 当日利率收益 */
  DailyInterestIncome = 'dailyInterestIncome',
  /** 报错信息 */
  ErrorMessage = 'errorMessage',
  /** 执行时间 */
  ExecuteDateTime = 'executeDateTime',
  /** 是否最新 */
  IsNew = 'isNew',
  /** 已撤销 */
  Revert = 'revert',
  /** 资源名称 */
  FieldName = 'fieldName',
  /** 新值 */
  NewValue = 'newValue',
  /** 旧值 */
  OldValue = 'oldValue',
  /** 展示修改前后的值 */
  DiffTable = 'diffTable',
  /** 后端传的互换类型  最好不要用 */
  ProductType = 'productType',
  /** 修改生命周期的备注 */
  LifeCycleComment = 'lifeCycleComment',
  /** 权益收益方向 */
  EquityProfitDirection = 'equityProfitDirection',
  /** 利率收益方向 */
  InterestProfitDirection = 'interestProfitDirection',
  /** 标的名义数量 */
  CurrentAmount = 'currentAmount',
  /** 多头组合名义本金额 */
  LongSideTotalNotAmt = 'longSideTotalNotAmt',
  /** 多头组合市值 */
  LongSideTotalMarketValue = 'longSideTotalMarketValue',
  /** 空头组合名义本金额 */
  ShortSideTotalNotAmt = 'shortSideTotalNotAmt',
  /** 空头组合市值 */
  ShortSideTotalMarketValue = 'shortSideTotalMarketValue',
  /** 当日空头年化利率收益 */
  ShortSideDailyInterestIncome = 'shortSideDailyInterestIncome',
  /** 累计利率收益 */
  AccumulateInterestIncome = 'accumulateInterestIncome',
  /** 累计实现利率收益 */
  RealizedInterestIncome = 'realizedInterestIncome',
  /** 待实现利率收益 */
  UnrealizedInterestIncome = 'unrealizedInterestIncome',
  /** 合约价值 */
  ContractPresentValue = 'contractPresentValue',
  TaskName = 'taskName',
  ApproveGroupList = 'approveGroupList',
  ReviewTask = 'reviewTask',
  /** 信用风险敞口限额 */
  Credit = 'credit',
  /** 预付金余额(￥) */
  PrePaymentBalance = 'prePaymentBalance',
  /** 合约价值.合并(￥) */
  ContractNetPresentValue = 'contractNetPresentValue',
  /** 盯市金额(￥) */
  MarkToMarketAmount = 'markToMarketAmount',
  /** 维持保障金额(￥) */
  MaintenanceMargin = 'maintenanceMargin',
  /** 追加后保障金额(￥) */
  AfterAdditionalMargin = 'afterAdditionalMargin',
  /** 保障金状态 */
  MarginStatus = 'marginStatus',
  /** 应追加预付金金额(￥) */
  MarginCallAmount = 'marginCallAmount',
  /** 折算后合约价值(￥) */
  ConvertedContractPresentValue = 'convertedContractPresentValue',
  /** 多头盯市基准金额(￥) */
  LongSideMtmAmount = 'longSideMtmAmount',
  /** 空头盯市基准金额(￥) */
  ShortSideMtmAmount = 'shortSideMtmAmount',
  /** 初始保障金额(￥) */
  InitialMargin = 'initialMargin',
  /** 提取前保障金额(￥) */
  BeforeWithDrawalMargin = 'beforeWithdrawalMargin',
  /** 提取后保障金额(￥) */
  AfterWithDrawalMargin = 'afterWithdrawalMargin',
  /** 信用风险敞口限额占用 */
  CreditOccupy = 'creditOccupy',
  /** 信用风险敞口限额剩余 */
  CreditSurplus = 'creditSurplus',
  /** 数组形式的合约编号 */
  ContractCodes = 'contractCodes',
  Enhanced /** 信用风险敞口限额占用 */ = 'enhanced',
  /** 预付金支付方向 */
  MarginDirection = 'marginDirection',
  /** 多头初始预付金率 */
  LongSideInitialPrepaymentRate = 'longSideInitialPrepaymentRate',
  /** 空头初始预付金率 */
  ShortSideInitialPrepaymentRate = 'shortSideInitialPrepaymentRate',
  /** 实现利率收益 */
  InterestIncome = 'interestIncome',
  /** 实现基本费用 */
  ContractBaseInterestIncome = 'contractBaseInterestIncome',
  /** 平仓后名义数量 */
  AfterUnwindAmount = 'afterUnwindAmount',
  /** 合约结算名义本金额(￥) */
  ContractSettleNotionalAmount = 'contractSettleNotionalAmount',
  /** 修改日期 */
  AmendDate = 'amendDate',
  /** 合约平仓后名义本金额(￥) */
  ContractAfterUnwindNotionalAmount = 'contractAfterUnwindNotionalAmount',
  /** 实现权益收益.增强(￥) */
  EquityIncomeEnhance = 'equityIncomeEnhance',
  /** 实现合约权益收益.增强(￥) */
  ContractEquityIncomeEnhance = 'contractEquityIncomeEnhance',
  /** 业务类型 */
  BusinessType = 'businessType',
  /** 初始预付金支付日 */
  InitialMarginPaymentDate = 'initialMarginPaymentDate',
  /** 实现合约权益收益.浮动(￥) */
  ContractEquityIncomeFloat = 'contractEquityIncomeFloat',
  /** 支付方式 */
  PaymentMethod = 'paymentMethod',

  /** 当日权益收益.增强 */
  OneDayEnhanceIndexIncome = 'oneDayEnhanceIndexIncome',
  /** 当日权益收益.浮动 */
  OneDayEquityIncome = 'oneDayEquityIncome',
  /** 当日权益收益.股息 */
  OneDayDividends = 'oneDayDividends',
  /** 待实现权益收益.浮动 */
  UnrealizedEquityIncome = 'unrealizedEquityIncome',
  /** 待实现权益收益.增强 */
  UnrealizedEnhanceIndexIncome = 'unrealizedEnhanceIndexIncome',
  /** 待实现权益收益.股息 */
  UnrealizedDividends = 'unrealizedDividends',
  /** 累计实现权益收益 */
  RealizedCashFlow = 'realizedCashFlow',
  /** 累计实现权益收益.增强 */
  RealizedEnhanceIndexIncome = 'realizedEnhanceIndexIncome',
  /** 累计实现权益收益.股息 */
  RealizedDividends = 'realizedDividends',
  /** 当日实现合约利率收益 */
  NewlyRealizedInterestIncome = 'newlyRealizedInterestIncome',
  /** 模板名称 */
  TemplateName = 'templateName',
  /** 模板类型 */
  TemplateType = 'templateType',
  /** 最近保存时间 */
  UpdateTime = 'updateTime',
  /** 交易货币 */
  TradingCurrency = 'tradingCurrency',
  /** 交易货币 */
  SettleCurrency = 'settleCurrency',
  /** 期初汇率 */
  InitExchangeRate = 'initExchangeRate',
  /** 参考汇率 */
  ReferenceExchangeRate = 'referenceExchangeRate',
  /** 汇率类型 */
  ExchangeRateType = 'exchangeRateType',
  /** 结算汇率 */
  SettleExchangeRate = 'settleExchangeRate',
  /** 平仓实现合约利率收益（结算货币） */
  SettleCurrencyTotalInterestIncome = 'settleCurrencyTotalInterestIncome',
  /** 平仓实现合约权益收益（结算货币） */
  SettleCurrencyTotalEquityIncome = 'settleCurrencyTotalEquityIncome',
  /** 当日汇率 */
  TodayExchangeRate = 'todayExchangeRate',
  /** 当日实现权益收益(结算货币) */
  NewlyRealizedCashFlowSettle = 'newlyRealizedCashFlowSettle',
  /** 累计实现权益收益(结算货币) */
  RealizedCashFlowSettle = 'realizedCashFlowSettle',
  /** 待实现权益收益(结算货币) */
  UnrealizedCashFlowSettle = 'unrealizedCashFlowSettle',
  /** 当日实现利率收益(结算货币) */
  NewlyRealizedInterestIncomeSettle = 'newlyRealizedInterestIncomeSettle',
  /** 累计实现利率收益(结算货币) */
  RealizedInterestIncomeSettle = 'realizedInterestIncomeSettle',
  /** 待实现利率收益(结算货币) */
  UnrealizedInterestIncomeSettle = 'unrealizedInterestIncomeSettle',
  /** 合约价值(结算货币) */
  ContractPresentValueSettle = 'contractPresentValueSettle',
  /** 累计合约利率收益(结算货币) */
  AccumulateInterestIncomeSettle = 'accumulateInterestIncomeSettle',
  /** 当日合约利率收益(结算货币) */
  DailyInterestIncomeSettle = 'dailyInterestIncomeSettle',
  /** 交易方向-角色 */
  SwapRole = 'swapRole',
  /** 权益方向 */
  SwapEquityDirection = 'swapEquityDirection',
  /** 利率方向 */
  SwapInterestDirection = 'swapInterestDirection',

  /** 合约价值.合并(结算货币) */
  SettleCurrencyContractNetPresentValue = 'settleCurrencyContractNetPresentValue',
  /** 折算后合约价值(结算货币) */
  SettleCurrencyConvertedContractPresentValue = 'settleCurrencyConvertedContractPresentValue',
  /** 初始保障金额(结算货币) */
  SettleCurrencyInitialMargin = 'settleCurrencyInitialMargin',
  /** 维持保障金额(结算货币) */
  SettleCurrencyMaintenanceMargin = 'settleCurrencyMaintenanceMargin',
  /** 追加后保障金额(结算货币) */
  SettleCurrencyAfterAdditionalMargin = 'settleCurrencyAfterAdditionalMargin',
  /** 提取前保障金额(结算货币) */
  SettleCurrencyBeforeWithDrawalMargin = 'settleCurrencyBeforeWithdrawalMargin',
  /** 提取后保障金额(结算货币) */
  SettleCurrencyAfterWithDrawalMargin = 'settleCurrencyAfterWithdrawalMargin',
  /** 合约价值(结算货币) */
  SettleCurrencyContractPresentValue = 'settleCurrencyContractPresentValue',
  /** 多头盯市基准金额(结算货币) */
  SettleCurrencyLongSideMtmAmount = 'settleCurrencyLongSideMtmAmount',
  /** 空头盯市基准金额(结算货币) */
  SettleCurrencyShortSideMtmAmount = 'settleCurrencyShortSideMtmAmount',
  /** 合约类型 */
  ContractType = 'contractType',
  /** 框架合约编号 */
  FwContractCode = 'fwContractCode',
  /** 合约固定收益率 */
  ContractFixRate = 'contractFixRate',
  /** 合约估值调整项 */
  ContractValueAdj = 'contractValueAdj',
  /** 盯市基准 */
  MtmReference = 'mtmReference',
  /** 初始保障比例参数 */
  InitialMarginRatio = 'initialMarginRatio',
  /** 维持保障比例参数 */
  MaintenanceMarginRatio = 'maintenanceMarginRatio',
  /** 初始预付金率 */
  InitialPrepaymentRate = 'initialPrepaymentRate',
  /** 锁定期 */
  LockupPeriod = 'lockupPeriod',
  /** 资金账户 */
  CapitalAccountId = 'capitalAccountId',
  /** 交易日历 */
  CalendarId = 'calendarId',
  /** 标的名称 */
  UnderlyingInstrumentName = 'underlyingInstrumentName',
  /** 多头计息基准表达式 */
  LongSideIrAccRefExp = 'longSideIrAccRefExp',
  /** 空头计息基准表达式 */
  ShortSideIrAccRefExp = 'shortSideIrAccRefExp',
  /** 计息基准表达式 */
  IrAccRefExp = 'irAccRefExp',
  /** 预留字段 */
  ReservedField = 'reservedField',
  /** 期限 */
  Term = 'term',
  /** 参与率 */
  ParticipationRate = 'participationRate',
  /** 平仓线 */
  UnwindLine = 'unwindLine',
  /** 多头平仓线 */
  LongSideUnwindLine = 'longSideUnwindLine',
  /** 空头平仓线 */
  ShortSideUnwindLine = 'shortSideUnwindLine',
  /** 自定义字段 */
  Customize = 'customize',
  /** 提前终止费率 */
  UnwindRate = 'unwindRate',
}

export { SwapFieldNameEnums };
