import { SwapFieldNameEnums } from './fields';

/** 簿记字段先后顺序 */
const sortList = [
  SwapFieldNameEnums.TradeConfirmId,
  SwapFieldNameEnums.SwapRole,
  SwapFieldNameEnums.SwapEquityDirection,
  SwapFieldNameEnums.SwapInterestDirection,
  SwapFieldNameEnums.TradingCurrency,
  SwapFieldNameEnums.SettleCurrency,
  SwapFieldNameEnums.InitExchangeRate,
  SwapFieldNameEnums.ReferenceExchangeRate,
  SwapFieldNameEnums.ExchangeRateType,
  SwapFieldNameEnums.TradeDate,
  SwapFieldNameEnums.EffectiveDate,
  SwapFieldNameEnums.ExpirationDate,
  SwapFieldNameEnums.SettlementDate,
  SwapFieldNameEnums.InterestPayFrequency,
  SwapFieldNameEnums.InterestIncomeDeadLine,
  SwapFieldNameEnums.DaysInYear,
  SwapFieldNameEnums.ContractFixRate,
  SwapFieldNameEnums.FixRate,
  SwapFieldNameEnums.LongSideInterestAccrualReference,
  SwapFieldNameEnums.LongSideFixRate,
  SwapFieldNameEnums.LongSideFloatIndex,
  SwapFieldNameEnums.LongSideFloatRates,
  SwapFieldNameEnums.LongSideLimitRates,
  SwapFieldNameEnums.ShortSideInterestAccrualReference,
  SwapFieldNameEnums.InitNotionalAmount,
  SwapFieldNameEnums.ContractNotionalAmount,
  SwapFieldNameEnums.MtmReference,
  SwapFieldNameEnums.InitialMarginRatio,
  SwapFieldNameEnums.MaintenanceMarginRatio,
  SwapFieldNameEnums.LongSideMtmReference,
  SwapFieldNameEnums.LongSideInitialMarginRatio,
  SwapFieldNameEnums.LongSideMaintenanceMarginRatio,
  SwapFieldNameEnums.ShortSideMtmReference,
  SwapFieldNameEnums.ShortSideInitialMarginRatio,
  SwapFieldNameEnums.ShortSideMaintenanceMarginRatio,
  SwapFieldNameEnums.AdditionalMarginRatio,
  SwapFieldNameEnums.BeforeWithdrawalMarginRatio,
  SwapFieldNameEnums.AfterWithdrawalMarginRatio,
  SwapFieldNameEnums.ConversionRate,
  SwapFieldNameEnums.MarginDirection,
  SwapFieldNameEnums.InitialPrepaymentRate,
  SwapFieldNameEnums.LongSideInitialPrepaymentRate,
  SwapFieldNameEnums.ShortSideInitialPrepaymentRate,
  SwapFieldNameEnums.ContractInitialMarginAmount,
  SwapFieldNameEnums.InitialMarginPaymentDate,
  SwapFieldNameEnums.Comment,
];

export { sortList };
